package commands;

public enum CommandName {
    ADD,
    CLEAR,
    COUNT_GREATER_THAN_DISTANCE,
    EXECUTE_SCRIPT,
    EXIT,
    HELP,
    INFO,
    PRINT_FIELD_ASCENDING_DISTANCE,
    REMOVE_ALL_BY_DISTANCE,
    REMOVE_BY_ID,
    REMOVE_FIRST,
    REMOVE_GREATER,
    REMOVE_LOWER,
    SHOW,
    UPDATE,
    SAVE,
    UNDEFINED
}
